Lab3 Харьковский К.В.
Brarion/front-course-bgu pull request #14
Opened 2024-03-29 20:04 UTC by NoK1R1LL

2024-04-18 07:42 UTC, Brarion requested changes

2024-04-18 07:42 UTC, Brarion commented on lab3/Mat.html
> +        var Length = function (arr) { return arr.length; };
Тут нужно использовать ts

2024-05-01 22:13 UTC, NoK1R1LL commented on lab3/Mat.html
> +        var Length = function (arr) { return arr.length; };
Исправил

2024-05-02 05:47 UTC, Brarion commented
Сдано

2024-05-02 05:47 UTC, closed without merging